
@json=Content-Type: application/json

###

GET {{url}}

####
#post {{url}}
#
#### 查询所有用户
#get {{url}}/users
#
### 注册
POST {{url}}/register
{{json}}

{
  "username": "user4",
  "password": "123456"
}

#### 登录
#post {{url}}/login
#{{json}}
#
#{
#  "username": "user4",
#  "password": "123456"
#}
#
#### 个人信息
#get {{url}}/profile
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDc1ODcyOTM2Mjg2NWE0MDk4YmRhYSIsImlhdCI6MTU4MTczNTAyM30.Nm6UhPY7EfP-WQIDFldayXzFoJlt5oIgVhidzDPy0gc